[package]
name = "wh1409_dri_rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes="1.1.0"
unicode-segmentation="1.8.0"
chrono="0.4.0"
